version: "3.9"
services:
  
  simulator:
    build: ./simulator
    container_name: simulator
    ports:
      - "3000:3000"
    volumes:
      - ./simulator:/app
    depends_on:
      - redis
    restart: always

  dashboard-server:
    build: ./dashboard-server
    container_name: dashboard-server
    ports:
      - "3001:3000"
    volumes:
      - ./dashboard-server:/app
    depends_on:
      - redis
    restart: always

  insights-server:
    build: ./insights-server
    container_name: insights-server
    ports:
      - "3002:3000"
    volumes:
      - ./insights-server:/app
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:6"
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
